### ISSUE TITLE
hallo saya mengalamai erorr, cara mengatasinya bagaimna

### ISSUE THREAD

**Issue by fannyputra80** [ifirmawan/indeks-kami#11]
![image](https://user-images.githubusercontent.com/45403055/111728953-8c01b880-88a0-11eb-9e2e-f706d8fb9c23.png)

**Comment by ifirmawan** [comment]
Hallo @fannyputra80 
Bisa dicek di pull request terkait perubahan apa saja yang dilakukan ya. kalo sudah bisa langsung
```
git pull origin master
```
kemudian 
```
php artisan migrate:fresh
php artisan db:seed
```
